# =========================
# LIMPIEZA
# =========================
TMP_DAYS=7

# =========================
# BACKUP (RSYNC)
# =========================
BACKUP_SOURCE="${HOME}/backup_source"
BACKUP_DEST="${HOME}/backups"

# =========================
# SERVICIOS
# =========================
SERVICES=("nginx" "apache2")

# =========================
# DOCKER
# =========================
CONTAINER_NAME="web_test"
